[package]
name = "playe-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
flexbuffers = "2.0.0"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
ron = "0.8"
bson = "2.11.0"
rmp-serde = "1.3.0"
